# Generated by Django 4.2.5 on 2024-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiling", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name="homepage",
        ),
    ]
