# Generated by Django 4.2.5 on 2024-03-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiling", "0004_remove_product_quantity_remove_product_total_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="quantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
            ],
        ),
    ]
