# Generated by Django 4.2.5 on 2024-03-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Profiling", "0005_quantity"),
    ]

    operations = [
        migrations.DeleteModel(
            name="quantity",
        ),
        migrations.AddField(
            model_name="product",
            name="prototal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
